notifications:
  email: false

sudo: false

cache:
  directories:
    - .composer/cache

language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer -n selfupdate
  - composer -n --prefer-source install
  - composer -n --prefer-source require satooshi/php-coveralls

script:
  - bin/test --coverage-clover=build/logs/clover.xml

after_success:
  - vendor/bin/coveralls -v
