name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
        dependencies:
          - hi
          - lo

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Validate composer.json
        run: composer validate

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-${{ matrix.php }}-${{ matrix.dependencies }}-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-${{ matrix.dependencies }}-

      - name: Install dependencies ${{ matrix.dependencies == 'lo' && '(lowest)' || '' }}
        run: composer update --no-interaction --no-progress
          ${{ matrix.dependencies == 'lo' && '--prefer-lowest' || '' }}

      - name: Run test suite with coverage
        run: composer test -- --coverage-clover=build/logs/clover.xml

      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
